name: Run tests
on:
  - push
  - pull_request
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.2
      - run: Rscript -e 'print("hello")'
