name: Run tests
on:
  - push
  - pull_request
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.2
      - name: Install dependencies
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::activate()'
          Rscript -e 'renv::install("DocEd/commonEHR")'
          Rscript -e 'renv::install("DocEd/wranglEHR")'
          Rscript -e 'renv::install(".")'
